(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ac-auto-show-menu 0.2)
 '(ac-auto-start 5)
 '(ac-candidate-limit nil)
 '(ac-stop-words (quote ("$this")))
 '(ac-use-fuzzy t)
 '(ac-use-menu-map t)
 '(ac-use-overriding-local-map nil)
 '(anything-c-adaptive-history-length 100)
 '(anything-c-boring-file-regexp "/\\(?:\\(?:\\.\\(?:git\\|hg\\|svn\\|\\backup\\)\\|CVS\\|_darcs\\)\\)\\(?:/\\|$\\)\\|^\\.#\\|\\(?:\\(?:\\.\\(?:class\\|la\\|o\\)\\|~\\)\\)$")
 '(anything-c-default-external-file-browser "conkeror")
 '(anything-c-use-adaptative-sorting nil)
 '(anything-command-map-prefix-key "M-<down>")
 '(browse-url-firefox-program "firefox")
 '(cscope-do-not-update-database t)
 '(eshell-buffer-maximum-lines 10000)
 '(flymake-gui-warnings-enabled nil)
 '(flymake-log-level -1)
 '(flymake-no-changes-timeout 0.5)
 '(globalff-regexp-search t)
 '(grep-command "grep --color --exclude=\"TAGS\" --exclude=\"\\.gitmodules\" --exclude=\"cscope.files\" --exclude=\"cscope.out\" --exclude=\"GPATH\" --exclude=\"GRTAGS\" --exclude=\"GTAGS\" --exclude-dir=\"*git*\" -nsH2re ")
 '(grep-find-command "find . -type f -not -path '*.git*' -a -not -name TAGS -a -not -name '*#' -a -not -name '*.log' -a -not -name \"cscope.files\" -a -not -name \"cscope.out\" -a -not -name \"GPATH\" -a -not -name \"GRTAGS\" -a -not -name \"GTAGS\" -print0 | xargs -0 grep -n -e ")
 '(grep-find-ignored-files (quote (".#*" "*.o" "*~" "*.bin" "*.lbin" "*.so" "*.a" "*.ln" "*.blg" "*.bbl" "*.elc" "*.lof" "*.glo" "*.idx" "*.lot" "*.fmt" "*.tfm" "*.class" "*.fas" "*.lib" "*.mem" "*.x86f" "*.sparcf" "*.fasl" "*.ufsl" "*.fsl" "*.dxl" "*.pfsl" "*.dfsl" "*.p64fsl" "*.d64fsl" "*.dx64fsl" "*.lo" "*.la" "*.gmo" "*.mo" "*.toc" "*.aux" "*.cp" "*.fn" "*.ky" "*.pg" "*.tp" "*.vr" "*.cps" "*.fns" "*.kys" "*.pgs" "*.tps" "*.vrs" "*.pyc" "*.pyo" "TAGS" "*#")))
 '(grep-find-template "find . <X> -type f <F> -not -path '*.git*' -a -not -name TAGS -a -not -name '*#' -a -not -name '*.log' -a -not -name \"cscope.files\" -a -not -name \"cscope.out\" -a -not -name \"GPATH\" -a -not -name \"GRTAGS\" -a -not -name \"GTAGS\" -print0 | xargs -0 -e grep <C> -n -e <R>")
 '(grep-highlight-matches (quote always))
 '(grep-scroll-output nil)
 '(gtags-path-style (quote absolute))
 '(gtags-suggested-key-mapping nil)
 '(history-delete-duplicates nil)
 '(history-length 100)
 '(icomplete-mode t)
 '(ido-enable-flex-matching t)
 '(ido-enable-regexp t)
 '(ido-everywhere t)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(initial-buffer-choice "~/")
 '(js-flat-functions nil)
 '(js2-basic-offset 4)
 '(js2-include-node-externs t)
 '(js2-mirror-mode nil)
 '(locate-command "locate --regex")
 '(make-backup-files nil)
 '(mk-proj-ack-cmd "ack")
 '(partial-completion-mode nil)
 '(php-mode-force-pear t)
 '(remote-shell-program "zsh")
 '(savehist-mode t nil (savehist))
 '(term-input-autoexpand (quote history))
 '(terminal-redisplay-interval 1000)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(uniquify-min-dir-content 0)
 '(use-file-dialog nil)
 '(viper-insert-state-cursor-color "Yellow")
 '(w3m-default-display-inline-images t)
 '(w3m-home-page "http://google.fr")
 '(w3m-lnum-quick-browsing (quote quick-all))
 '(w3m-new-session-url "http://google.fr")
 '(w3m-use-cookies t)
 '(w3m-use-title-buffer-name t)
 '(w3m-user-agent "Mozilla/5.0 (compatible; Windows; U; Windows NT 6.2; WOW64; en-US; rv:12.0) Gecko/20120403211507 Firefox/12.0"))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(ac-completion-face ((t (:background "black" :foreground "red" :underline t))))
 '(ac-etags-candidate-face ((t (:background "gainsboro" :foreground "green4"))))
 '(ac-etags-selection-face ((t (:background "green4" :foreground "white"))))
 '(ac-gtags-candidate-face ((t (:background "blue3" :foreground "yellow2"))))
 '(ac-gtags-selection-face ((t (:background "yellow3" :foreground "blue3"))))
 '(cursor ((t (:background "yellow"))))
 '(diredp-compressed-file-suffix ((t (:background "Purple" :foreground "Yellow" :weight bold))))
 '(diredp-date-time ((t (:background "White" :foreground "DarkGoldenrod4"))))
 '(diredp-deletion-file-name ((t (:background "White" :foreground "Red"))))
 '(diredp-dir-priv ((t (:background "LightGray" :foreground "DarkRed" :underline "red" :weight extra-bold))))
 '(diredp-display-msg ((t (:background "Orange" :foreground "Blue" :weight bold))))
 '(diredp-executable-tag ((t (:background "White" :foreground "Red" :weight bold))))
 '(diredp-file-name ((t (:background "Grey" :foreground "Blue" :weight bold))))
 '(diredp-file-suffix ((t (:background "Grey" :foreground "Black" :weight bold))))
 '(diredp-inode+size ((t (:background "Grey" :foreground "DarkGreen" :weight bold))))
 '(diredp-symlink ((t (:background "White" :foreground "DarkOrange" :weight bold))))
 '(flymake-errline ((((class color) (background dark)) (:overline "red" :underline "red" :weight semi-bold))))
 '(flymake-warnline ((((class color) (background dark)) (:overline "blue" :underline "blue" :weight semi-bold))))
 '(magit-branch ((t (:inherit nil :background "orange" :weight bold))))
 '(magit-diff-add ((((class color) (background dark)) (:foreground "green"))))
 '(magit-diff-del ((((class color) (background dark)) (:foreground "red"))))
 '(magit-diff-file-header ((t (:inherit magit-header :foreground "green"))))
 '(magit-diff-hunk-header ((t (:inherit magit-header :foreground "RoyalBlue4" :slant italic))))
 '(magit-diff-none ((t (:foreground "white"))))
 '(magit-header ((t (:foreground "yellow"))))
 '(magit-item-highlight ((((class color) (background dark)) (:background "gray23"))))
 '(magit-log-message ((t (:foreground "white" :weight bold))))
 '(magit-section-title ((t (:inherit nil :foreground "orange" :weight bold)))))
