(setq package-list '
      (
       ack
       ack-and-a-half
       anyins
       autopair
       browse-kill-ring
       clojure-mode
       cider
       codesearch
       color-theme
       company
       dired+
       emamux
       eyuml
       feature-mode
       flycheck
       grep-a-lot
       gtags
       ggtags
       haskell-mode
       helm-ack
       helm-backup
       helm-cscope
       helm-gtags
       helm-projectile
       helm-swoop
       helm
       http-twiddle
       ido-vertical-mode
       js2-mode
       magit
       git-rebase-mode
       git-commit-mode
       markdown-mode+
       markdown-mode
       multiple-cursors
       paredit
       php-mode
       popup
       projectile
       pkg-info
       epl
       dash
       request
       s
       shell-pop
       switch-window
       twig-mode
       undo-tree
       web-mode
       wgrep
       ws-trim
       xclip
       yaml-mode
       zencoding-mode))
