(setq package-list '
      (
       ack
       ack-and-a-half
       ag
       anyins
       auto-complete
       autopair
       browse-kill-ring
       clojure-mode
       cider
       color-moccur
       color-theme
       dired+
       emamux
       eyuml
       feature-mode
       flycheck
       gtags
       haskell-mode
       helm-ack
       helm-backup
       helm-gtags
       helm-projectile
       helm
       http-twiddle
       ido-vertical-mode
       js2-mode
       magit
       git-rebase-mode
       git-commit-mode
       markdown-mode+
       markdown-mode
       multiple-cursors
       paredit
       php-mode
       popup
       projectile
       pkg-info
       epl
       dash
       request
       s
       shell-pop
       switch-window
       twig-mode
       twittering-mode
       undo-tree
       wgrep
       ws-trim
       xclip
       yaml-mode
       zencoding-mode))
