(setq package-list '
      (
       ack
       ack-and-a-half
       ag
       ascope
       auto-complete
       autopair
       browse-kill-ring
       clojure-test-mode
       cider
       color-moccur
       color-theme
       dired+
       emamux
       feature-mode
       flymake-php
       flymake-easy
       gtags
       helm-ack
       helm-backup
       helm-gtags
       helm-projectile
       helm
       http-twiddle
       ido-vertical-mode
       js2-mode
       magit
       git-rebase-mode
       git-commit-mode
       markdown-mode+
       markdown-mode
       multiple-cursors
       nrepl
       clojure-mode
       paredit
       php-mode
       popup
       projectile
       pkg-info
       epl
       dash
       request
       s
       shell-pop
       switch-window
       twittering-mode
       undo-tree
       wgrep
       ws-trim
       xclip
       yaml-mode
       zencoding-mode))
